name: chart versioning2

on: [push]




jobs:
  chart_versioning2:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Get base ref branch
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        
      - name: Get PR number
        id: action
        uses: kamatama41/get-pr-number-action@v0
 #     - name: Automated version update
 #       run: sed -i -E 's@(targetRevision:) (.*)@\1 '"${{ steps.action.outputs.number }}-${{ steps.branch-name.outputs.base_ref_branch }}"'@g' version.txt
      - uses: actions/checkout@v3
      - name: Automated version update
        
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git fetch
         git checkout ${{ steps.branch-name.outputs.current_branch }}
         sed -i -E 's@(targetRevision:) (.*)@\1 '"${{ steps.action.outputs.number }}-${{ steps.branch-name.outputs.base_ref_branch }}"'@g' version.txt
         git add .
         if [ -n "$(git status --porcelain)" ]; then
             git commit -m "update the chart version"
             git push
         else
           echo "no changes";
         fi
      - name: Create status check
        env:
          GITHUB_TOKEN: ${{ secrets.KEY }}
        run: |
          BUILD_COMMIT=$(git rev-parse HEAD)
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ehabzaki/argocd-vault-plugin/check-runs \
          -d '{"name":"build", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "success" }'
          
      - name: Staging Tests ✅
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.KEY }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "chart_versioning2",
            "state": "success",
            "description": "chart_versioning2",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
#       - name: commit changes
#         #if: ${{ job.status != 'success' }}
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           message: "update the chart version"
#       - name: Check success
#         if: ${{ always() }}
#         run: echo [skip ci] 
             
#       - name: commit changes
#         uses: EndBug/add-and-commit@v9
#         with:
#           message:: "update the chart version"
#           pathspec_error_handling: ignore
#       - name: Check success
#         if: ${{ always() }}
#         run: echo [skip ci]
