name: chart versioning2

on: [push]




jobs:
  chart_versioning2:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Get base ref branch
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        
      - name: Get PR number
        id: action
        uses: kamatama41/get-pr-number-action@v0
 #     - name: Automated version update
 #       run: sed -i -E 's@(targetRevision:) (.*)@\1 '"${{ steps.action.outputs.number }}-${{ steps.branch-name.outputs.base_ref_branch }}"'@g' version.txt
      - uses: actions/checkout@v3
      - name: Automated version update
        
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git fetch
         git checkout ${{ steps.branch-name.outputs.current_branch }}
         sed -i -E 's@(targetRevision:) (.*)@\1 '"${{ steps.action.outputs.number }}-${{ steps.branch-name.outputs.base_ref_branch }}"'@g' version.txt
         git add .
         if [ -n "$(git status --porcelain)" ]; then
             git commit -m "update the chart version"
             git push
         else
           echo "no changes";
         fi
             
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
#       - name: commit changes
#         #if: ${{ job.status != 'success' }}
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           message: "update the chart version"
#       - name: Check success
#         if: ${{ always() }}
#         run: echo [skip ci] 
             
#       - name: commit changes
#         uses: EndBug/add-and-commit@v9
#         with:
#           message:: "update the chart version"
#           pathspec_error_handling: ignore
#       - name: Check success
#         if: ${{ always() }}
#         run: echo [skip ci]
